"""empty message

Revision ID: 0b1367ac6a51
Revises: c653c6c56dfe
Create Date: 2022-03-29 13:42:11.090597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1367ac6a51'
down_revision = 'c653c6c56dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'share')
    op.drop_constraint('user_profile_image_url_key', 'user', type_='unique')
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_profile_image_url_key', 'user', ['profile_image_url'])
    op.add_column('list', sa.Column('share', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
