"""empty message

Revision ID: 491cac6ea2b2
Revises: 2de7cee5767c
Create Date: 2022-02-23 18:47:19.350459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491cac6ea2b2'
down_revision = '2de7cee5767c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user', ['profile_image_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###
