"""empty message

Revision ID: c653c6c56dfe
Revises: aa2658fa6598
Create Date: 2022-03-26 15:35:18.937094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c653c6c56dfe'
down_revision = 'aa2658fa6598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'index')
    # ### end Alembic commands ###
